In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
Independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [6]:
Dependent=dataset[["charges"]]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(Independent,Dependent,test_size=0.30,random_state=0)

In [40]:
from sklearn.ensemble import GradientBoostingRegressor
Regressor=GradientBoostingRegressor(n_estimators=50,random_state=0)
Regressor=Regressor.fit(x_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\ensemble\_gb.py:672: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)  # TODO: Is this still required?

In [41]:
y_pred=Regressor.predict(x_test)

In [42]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [43]:
r_score

0.8914914042698048

In [46]:
import pickle
filename="Finalized_model_LG.sav"

In [47]:
pickle.dump(Regressor,open(filename,'wb'))

In [48]:
loaded_model=pickle.load(open("Finalized_model_LG.sav",'rb'))
result=loaded_model.predict([[29,25.330,2,False,True]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GradientBoostingRegressor was fitted with feature names
  warnings.warn(

In [49]:
result

array([17812.70583371])